include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_return: error
    missing_required_param: error

    avoid_print: ignore

  exclude:
    - "**.*.g.dart"
    - "**.*.freezed.dart"